
//var p = new Parent(45);
//var p2 = new Parent(34);
//var gp = new GrandParent();
//var c = new Child();
//var gc = new GrandChild('bob',34);
//var ggc = new GreatGrandChild('bob',14);
//var ggc = new GreatGrandChild('tim', 56);
var ggc = GreatGrandChild();
var ggc2 = new GreatGrandChild();
//alert(gp.getId());
//alert(p);
//alert (p.getAge());
//alert( ggc.getId());
//alert(ggc._super('getId'));
//alert(ggc._super('_super',['getId']));
//alert(ggc._super('_super',['_super',['getId']]));
//alert(ggc._super('_super',['_super',['_super',['getId',[]]]]));
//ggc._super('changePrivate',['privateChanged']);
//alert(ggc._super('getPrivate'));
//ggc.changePrivate('changedAgain');
//alert(ggc.getPrivate());
//alert(ggc2.getPrivate());
//console.log(ggc.getWeight());
//alert(gcc.getWeight());
//console.log(ggc._super);
//alert(p._super());
//alert(ggc._super.toString());
//alert(ggc._super.getPrivate());
//ggc.changePrivate("changed");
////alert(ggc._super.getPrivate());
//alert(ggc.getPrivate());
//alert(ggc2.getPrivate());
//ggc.changePrivate("privateChanged");
////alert(ggc.getPrivate());
//alert(ggc2.getPrivate());
//ggc._super._super._super._super.changePrivate("changed");
//alert(ggc._super._super._super._super.getPrivate());
//alert(ggc._super._super.toSource());
//alert(ggc._super._super._super._super._super.toSource());
//alert(ggc._super._super.getId());
alert(ggc.get_numInsts());
//alert(ggc.get_numInsts);
alert(ggc2.get_numInsts());
alert(ggc.get_numInsts());
